version: '2'
services:
    flask:
        build: .
        volumes:
            - .:/web
        expose:
            - "8000"
    nginx:
        build: ./nginx
        ports:
            - "9090:80"
        depends_on:
        - flask
