version: '2'
services:
    web:
        build: .
        ports:
            - "5000:8000"
        volumes:
            - .:/web
        environment:
            - PORT:5000

    nginx:
        build: ./nginx
        ports:
            - "8080:80"
            - "443:443"
